USE TURISMO
GO
/*
 P01R01_APIViajes_Saurio_AEHM
 AUTOR: ADRIAN ELEUTERIO HERNANDEZ MARTINEZ
 FECHA: 04/09/2026
*/

--=============================
-- ELIMINAR TABLAS
--=============================

--COMMIT Y ROLLBACK
BEGIN TRANSACTION
	BEGIN TRY
		--VALIDACIONES - ELIMINAR EN ORDEN INVERSO DE DEPENDENCIAS
		--TABLA: tblDestino
		IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblDestino'
			AND TABLE_SCHEMA = 'dbo')
			BEGIN
				DROP TABLE tblDestino;
				PRINT 'Tabla tblDestino eliminada correctamente'
			END
		ELSE 
			BEGIN
				PRINT 'La tabla tblDestino no existe'
			END
		COMMIT TRANSACTION; --CONFIRMAR CAMBIOS
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
		THROW;
	END CATCH
GO