//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciasUsuario
    {
        public int IdPreferencia { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> DecadaPreferida { get; set; }
        public Nullable<int> IdGeneroFavorito { get; set; }
        public string ModoRecomendacion { get; set; }
    
        public virtual Generos Generos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
