/*
 P10R01_WS_AEHM
 AUTOR: ADRIAN ELEUTERIO HERNANDEZ MARTINEZ
 FECHA: 11/09/2026
*/

USE BD_Ejemplo
GO

--=============================
-- ELIMINAR TABLAS
--=============================

--COMMIT ROLLBACK
BEGIN TRANSACTION
	BEGIN TRY
		--VALIDACIONES - ELIMINAR EN ORDEN INVERSO DE DEPENDENCIAS
		--TABLA: Rutas
		IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Usuarios'
			AND TABLE_SCHEMA = 'dbo')
			BEGIN
				DROP TABLE Usuarios;
				PRINT 'Tabla Usuarios eliminada correctamente'
			END
		ELSE 
			BEGIN
				PRINT 'La tabla Usuarios no existe'
			END
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
		THROW;
	END CATCH
GO